//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailBanking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account_creation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_creation()
        {
            this.accnt_transactions = new HashSet<accnt_transactions>();
        }
    
        [Key]
        public Nullable<int> customerid { get; set; }
        public string accounttype1 { get; set; }
        public int accountid { get; set; }
        public string accountstatus { get; set; }
        public string statusmessage { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<long> amount { get; set; }
    
        public virtual customer_account_creation customer_account_creation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accnt_transactions> accnt_transactions { get; set; }
    }
}
