//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailBanking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Services.Description;

    public partial class login_bankexe
    {
        public int id { get; set; }
        [Required(ErrorMessage="Please enter the username")]
        [Display(Name = "User name")]
        public string username { get; set; }
        [Required(ErrorMessage = "Please enter the password")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string pwd { get; set; }
        public Nullable<System.DateTime> login_detail { get; set; }
        public string type { get; set; }
    }
}
